import Head from "next/head";
import {
  FullScreenNextMatch,
  OurPartners,
  BackSection,
  NewsHighlight,
  GamesGadget,
  VllazniaTv,
  NewsAndSocial,
  TableGadget,
  ShopGadget,
  Footer,
} from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>K.F Vllaznia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullScreenNextMatch />
      <OurPartners />
      <BackSection>
        <NewsHighlight />
        <GamesGadget />
        <VllazniaTv />
        <NewsAndSocial />
        <TableGadget />
        <ShopGadget />
      </BackSection>
      <Footer />
    </div>
  );
}
