import Head from "next/head";
import { useEffect, useState } from "react";
import {
  FullScreenNextMatch,
  OurPartners,
  BackSection,
  NewsHighlight,
  GamesGadget,
  VllazniaTv,
  NewsAndSocial,
  TableGadget,
  ShopGadget,
  Footer,
} from "../components";
import {
  getMatches,
  getGallery,
  getNews,
  getProducts,
  getVideos,
} from "../pages/api/api";

export default function Home({ matches, gallery, news, products, videos }) {
  const [width, setWidth] = useState(null);

  useEffect(() => {
    setWidth(window.innerWidth);
  }, []);

  return (
    <div>
      <Head>
        <title>K.F Vllaznia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FullScreenNextMatch matches={matches} />
      <OurPartners />
      <BackSection>
        <NewsHighlight news={news} />
        <GamesGadget width={width} matches={matches} />
        <VllazniaTv videos={videos} />
        <NewsAndSocial gallery={gallery} news={news} />
        <TableGadget />
        <ShopGadget products={products} />
      </BackSection>
      <Footer />
    </div>
  );
}

export async function getStaticProps() {
  const matches = (await getMatches()) || [];
  const gallery = (await getGallery()) || [];
  const news = (await getNews()) || [];
  const products = (await getProducts()) || [];
  const videos = (await getVideos()) || [];
  return {
    props: {
      matches,
      gallery,
      news,
      products,
      videos,
    },
  };
}
